matrix:
  include:
    - language: java
      before_script:
        - cd backend
    - language: node_js
      before_script:
        - cd frontend
      script:
        - npm install
        - npm run build