matrix:
  include:
    - language: java
      before_script:
        - cd backend
    - language: node_js
      node_js: "stable"
      before_script:
        - cd frontend
      script:
        - npm install
        - npm test
        - CI=false npm run build